<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Tour;
use App\Models\TourImage;
use App\Models\Agency;
use App\Models\Category;
use Illuminate\Support\Str;

class ToursSeeder extends Seeder
{
    public function run(): void
    {
        $this->command->info('🎯 Creando tours...');

        $agencies = Agency::all();
        $categories = Category::all();

        $tours = [
            // ========== INCA ADVENTURES (Cusco) ==========
            [
                'agency_id' => $agencies[0]->id,
                'category_id' => $categories->where('name', 'Aventura')->first()->id,
                'title' => 'Camino Inca Clásico 4 Días a Machu Picchu',
                'description' => 'Experimenta la legendaria ruta del Camino Inca hacia Machu Picchu. Un viaje de 4 días atravesando paisajes andinos impresionantes, sitios arqueológicos incas y culminando con el amanecer en la ciudadela perdida de los Incas.',
                'itinerary' => "Día 1: Cusco - Km 82 - Wayllabamba (12km)\nSalida temprano desde Cusco. Inicio de caminata en el km 82. Almuerzo en ruta. Campamento en Wayllabamba (3,000 msnm).\n\nDía 2: Wayllabamba - Paso Warmihuañusca - Pacaymayo (11km)\nDía más desafiante. Ascenso al paso Warmihuañusca (4,215 msnm). Descenso a Pacaymayo. Vistas espectaculares.\n\nDía 3: Pacaymayo - Wiñay Wayna (16km)\nVisita a ruinas de Runkurakay y Sayacmarca. Paso por túnel inca. Campamento en Wiñay Wayna con vista a las ruinas.\n\nDía 4: Wiñay Wayna - Machu Picchu - Cusco\nSalida a las 4am hacia Inti Punku (Puerta del Sol). Amanecer en Machu Picchu. Tour guiado de 2 horas. Retorno a Cusco.",
                'includes' => "• Guía profesional bilingüe certificado\n• Entrada a Machu Picchu\n• Transporte Cusco - Km 82\n• Tren Aguas Calientes - Ollantaytambo\n• Bus Aguas Calientes - Machu Picchu\n• 3 noches de camping con carpas profesionales\n• Todas las comidas (3 desayunos, 3 almuerzos, 3 cenas)\n• Snacks y agua durante el trek\n• Porteadores para equipaje común\n• Botiquín de primeros auxilios\n• Oxígeno de emergencia",
                'excludes' => "• Propinas para guías y porteadores\n• Bebidas alcohólicas\n• Seguro de viaje personal\n• Porteador personal (disponible por USD 80)\n• Bastones de trekking (alquiler USD 15)\n• Entrada a Huayna Picchu (USD 75 adicional)\n• Sleeping bag (alquiler USD 20)",
                'requirements' => "• Buen estado físico (caminatas de 6-8 horas diarias)\n• Pasaporte vigente\n• Reservar con 6 meses de anticipación\n• Aclimatación de 2-3 días en Cusco\n• Edad mínima: 12 años\n• Vacuna contra fiebre amarilla (recomendada)",
                'cancellation_policy' => "Cancelación gratuita hasta 30 días antes. Entre 30-15 días: 50% de reembolso. Menos de 15 días: sin reembolso.",
                'refund_policy' => 'partial',
                'cancellation_hours' => 720,
                'price' => 650.00,
                'discount_price' => 580.00,
                'duration_days' => 4,
                'duration_hours' => 0,
                'max_people' => 16,
                'min_people' => 2,
                'difficulty_level' => 'hard',
                'location_city' => 'Cusco',
                'location_region' => 'Cusco',
                'location_country' => 'Peru',
                'latitude' => -13.163141,
                'longitude' => -72.545128,
                'featured_image' => 'https://images.unsplash.com/photo-1587595431973-160d0d94add1',
                'rating' => 4.9,
                'total_reviews' => 12,
                'total_bookings' => 8,
                'is_featured' => true,
                'is_active' => true,
                'is_published' => true,
                'published_at' => now(),
                'creation_step' => 5,
                'admin_verified' => true,
                'admin_verified_at' => now(),
                'available_days' => json_encode([1, 2, 3, 4, 5, 6, 0]),
                'quality_checklist' => json_encode([
                    'has_title' => true,
                    'has_description' => true,
                    'has_itinerary' => true,
                    'has_price' => true,
                    'has_images' => true,
                    'min_images_met' => true,
                ]),
                'images' => [
                    'https://images.unsplash.com/photo-1587595431973-160d0d94add1',
                    'https://images.unsplash.com/photo-1526392060635-9d6019884377',
                    'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b',
                    'https://images.unsplash.com/photo-1580619305218-8423a7ef79b4',
                ],
            ],
            [
                'agency_id' => $agencies[0]->id,
                'category_id' => $categories->where('name', 'Cultural')->first()->id,
                'title' => 'City Tour Cusco y Ruinas Cercanas',
                'description' => 'Descubre la capital del Imperio Inca en medio día. Visita la Catedral, Qoricancha, Sacsayhuamán, Q\'enqo, Puca Pucara y Tambomachay. Perfecto para tu primer día en Cusco.',
                'itinerary' => "13:00 - Recojo del hotel\n13:30 - Catedral de Cusco y Plaza de Armas\n14:30 - Qoricancha (Templo del Sol)\n15:30 - Sacsayhuamán (Fortaleza ceremonial)\n16:30 - Q'enqo (Centro ceremonial)\n17:00 - Puca Pucara (Fortaleza militar)\n17:30 - Tambomachay (Baños del Inca)\n18:30 - Retorno al hotel",
                'includes' => "• Transporte turístico compartido\n• Guía profesional español/inglés\n• Boleto Turístico (válido 10 días)\n• Entrada a la Catedral\n• Recojo y retorno al hotel",
                'excludes' => "• Almuerzo\n• Propinas\n• Gastos personales",
                'requirements' => "• No requiere aclimatación previa\n• Calzado cómodo\n• Protector solar y gorra\n• Cámara fotográfica",
                'cancellation_policy' => "Cancelación gratuita hasta 24 horas antes. Menos de 24h: sin reembolso.",
                'refund_policy' => 'partial',
                'cancellation_hours' => 24,
                'price' => 45.00,
                'discount_price' => 35.00,
                'duration_days' => 0,
                'duration_hours' => 5,
                'max_people' => 20,
                'min_people' => 2,
                'difficulty_level' => 'easy',
                'location_city' => 'Cusco',
                'location_region' => 'Cusco',
                'location_country' => 'Peru',
                'latitude' => -13.531950,
                'longitude' => -71.967463,
                'featured_image' => 'https://images.unsplash.com/photo-1526392060635-9d6019884377',
                'rating' => 4.7,
                'total_reviews' => 8,
                'total_bookings' => 15,
                'is_featured' => true,
                'is_active' => true,
                'is_published' => true,
                'published_at' => now(),
                'creation_step' => 5,
                'admin_verified' => true,
                'admin_verified_at' => now(),
                'available_days' => json_encode([1, 2, 3, 4, 5, 6, 0]),
                'quality_checklist' => json_encode([
                    'has_title' => true,
                    'has_description' => true,
                    'has_itinerary' => true,
                    'has_price' => true,
                    'has_images' => true,
                    'min_images_met' => true,
                ]),
                'images' => [
                    'https://images.unsplash.com/photo-1526392060635-9d6019884377',
                    'https://images.unsplash.com/photo-1580619305218-8423a7ef79b4',
                    'https://images.unsplash.com/photo-1587595431973-160d0d94add1',
                ],
            ],
            [
                'agency_id' => $agencies[0]->id,
                'category_id' => $categories->where('name', 'Trekking')->first()->id,
                'title' => 'Montaña de 7 Colores (Vinicunca) - Full Day',
                'description' => 'Visita una de las maravillas naturales más impresionantes del Perú. La montaña de colores Vinicunca ofrece paisajes únicos a 5,200 msnm. Una experiencia inolvidable para amantes del trekking.',
                'itinerary' => "04:00 - Recojo del hotel en Cusco\n06:30 - Desayuno en Cusipata\n08:00 - Inicio de caminata (2 horas)\n10:00 - Llegada a Vinicunca (5,200 msnm)\n10:30 - Tiempo libre para fotos\n12:00 - Descenso\n14:00 - Almuerzo buffet\n17:00 - Retorno a Cusco\n19:00 - Llegada a Cusco",
                'includes' => "• Transporte turístico ida y vuelta\n• Guía profesional\n• Desayuno y almuerzo buffet\n• Entrada a Vinicunca\n• Bastones de trekking\n• Botiquín y oxígeno",
                'excludes' => "• Caballos (opcional S/ 80)\n• Bebidas extras\n• Propinas\n• Desayuno del primer día",
                'requirements' => "• Buena condición física\n• Aclimatación de 2 días en Cusco\n• Ropa abrigadora\n• Bloqueador solar\n• Agua personal",
                'cancellation_policy' => "Cancelación gratuita hasta 48 horas antes.",
                'refund_policy' => 'full',
                'cancellation_hours' => 48,
                'price' => 70.00,
                'discount_price' => 55.00,
                'duration_days' => 1,
                'duration_hours' => 0,
                'max_people' => 15,
                'min_people' => 2,
                'difficulty_level' => 'hard',
                'location_city' => 'Cusco',
                'location_region' => 'Cusco',
                'location_country' => 'Peru',
                'latitude' => -13.869167,
                'longitude' => -71.302778,
                'featured_image' => 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b',
                'rating' => 4.8,
                'total_reviews' => 10,
                'total_bookings' => 18,
                'is_featured' => true,
                'is_active' => true,
                'is_published' => true,
                'published_at' => now(),
                'creation_step' => 5,
                'admin_verified' => true,
                'admin_verified_at' => now(),
                'available_days' => json_encode([1, 2, 3, 4, 5, 6, 0]),
                'quality_checklist' => json_encode([
                    'has_title' => true,
                    'has_description' => true,
                    'has_itinerary' => true,
                    'has_price' => true,
                    'has_images' => true,
                    'min_images_met' => true,
                ]),
                'images' => [
                    'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b',
                    'https://images.unsplash.com/photo-1441974231531-c6227db76b6e',
                    'https://images.unsplash.com/photo-1506905925346-21bda4d32df4',
                ],
            ],

            // ========== PERU MÁGICO (Lima) ==========
            [
                'agency_id' => $agencies[1]->id,
                'category_id' => $categories->where('name', 'Gastronomía')->first()->id,
                'title' => 'Tour Gastronómico Lima - Mercado + Clase de Ceviche',
                'description' => 'Sumérgete en la gastronomía peruana. Visita el mercado local, aprende a preparar ceviche auténtico y degusta los mejores sabores de Lima. Incluye pisco sour de bienvenida.',
                'itinerary' => "09:00 - Recojo en Miraflores/Barranco\n09:30 - Visita al mercado de Surquillo\n10:30 - Clase de cocina peruana\n11:00 - Preparación de ceviche clásico\n12:00 - Degustación y almuerzo\n13:30 - Clase de Pisco Sour\n14:30 - Retorno al hotel",
                'includes' => "• Chef instructor profesional\n• Ingredientes frescos del mercado\n• Pisco sour de bienvenida\n• Almuerzo completo con bebidas\n• Recetario digital\n• Certificado de participación\n• Delantal y gorro de chef",
                'excludes' => "• Transporte (disponible por S/ 30)\n• Propinas\n• Bebidas alcohólicas adicionales",
                'requirements' => "• No requiere experiencia culinaria\n• Edad mínima: 18 años para degustación de pisco\n• Avisar alergias alimentarias",
                'cancellation_policy' => "Cancelación gratuita hasta 24 horas antes.",
                'refund_policy' => 'full',
                'cancellation_hours' => 24,
                'price' => 95.00,
                'discount_price' => 75.00,
                'duration_days' => 0,
                'duration_hours' => 5,
                'max_people' => 12,
                'min_people' => 2,
                'difficulty_level' => 'easy',
                'location_city' => 'Lima',
                'location_region' => 'Lima',
                'location_country' => 'Peru',
                'latitude' => -12.046374,
                'longitude' => -77.042793,
                'featured_image' => 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1',
                'rating' => 4.9,
                'total_reviews' => 9,
                'total_bookings' => 12,
                'is_featured' => true,
                'is_active' => true,
                'is_published' => true,
                'published_at' => now(),
                'creation_step' => 5,
                'admin_verified' => true,
                'admin_verified_at' => now(),
                'available_days' => json_encode([2, 3, 4, 5, 6]),
                'quality_checklist' => json_encode([
                    'has_title' => true,
                    'has_description' => true,
                    'has_itinerary' => true,
                    'has_price' => true,
                    'has_images' => true,
                    'min_images_met' => true,
                ]),
                'images' => [
                    'https://images.unsplash.com/photo-1555939594-58d7cb561ad1',
                    'https://images.unsplash.com/photo-1559847844-5315695dadae',
                    'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38',
                ],
            ],
            [
                'agency_id' => $agencies[1]->id,
                'category_id' => $categories->where('name', 'Cultural')->first()->id,
                'title' => 'Lima Colonial y Moderna - City Tour',
                'description' => 'Conoce el contraste entre la Lima colonial y la moderna. Visita el centro histórico (Patrimonio UNESCO), Miraflores, Parque del Amor y el Circuito Mágico del Agua.',
                'itinerary' => "14:00 - Recojo en hotel\n14:30 - Plaza Mayor y Catedral de Lima\n15:30 - Convento de San Francisco y Catacumbas\n16:30 - Parque del Amor en Miraflores\n17:00 - Malecón de Miraflores\n17:30 - Larcomar (tiempo libre)\n18:30 - Circuito Mágico del Agua\n20:00 - Retorno al hotel",
                'includes' => "• Transporte turístico\n• Guía oficial bilingüe\n• Entrada a San Francisco\n• Entrada al Circuito Mágico del Agua\n• Recojo y retorno al hotel",
                'excludes' => "• Alimentos y bebidas\n• Propinas\n• Gastos personales",
                'requirements' => "• Ropa cómoda\n• Cámara fotográfica\n• Protector solar",
                'cancellation_policy' => "Cancelación gratuita hasta 24 horas antes.",
                'refund_policy' => 'full',
                'cancellation_hours' => 24,
                'price' => 55.00,
                'discount_price' => null,
                'duration_days' => 0,
                'duration_hours' => 6,
                'max_people' => 18,
                'min_people' => 2,
                'difficulty_level' => 'easy',
                'location_city' => 'Lima',
                'location_region' => 'Lima',
                'location_country' => 'Peru',
                'latitude' => -12.046374,
                'longitude' => -77.042793,
                'featured_image' => 'https://images.unsplash.com/photo-1531968455001-5c5272a41129',
                'rating' => 4.6,
                'total_reviews' => 6,
                'total_bookings' => 10,
                'is_featured' => false,
                'is_active' => true,
                'is_published' => true,
                'published_at' => now(),
                'creation_step' => 5,
                'admin_verified' => true,
                'admin_verified_at' => now(),
                'available_days' => json_encode([1, 2, 3, 4, 5, 6, 0]),
                'quality_checklist' => json_encode([
                    'has_title' => true,
                    'has_description' => true,
                    'has_itinerary' => true,
                    'has_price' => true,
                    'has_images' => true,
                    'min_images_met' => true,
                ]),
                'images' => [
                    'https://images.unsplash.com/photo-1531968455001-5c5272a41129',
                    'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5',
                    'https://images.unsplash.com/photo-1531572753322-ad063cecc140',
                ],
            ],

            // ========== AMAZONIA EXPEDITIONS (Iquitos) ==========
            [
                'agency_id' => $agencies[2]->id,
                'category_id' => $categories->where('name', 'Naturaleza')->first()->id,
                'title' => 'Expedición Amazonas 3 Días / 2 Noches - Lodge en la Selva',
                'description' => 'Vive la experiencia amazónica auténtica. Alojamiento en lodge ecológico, navegación por el río Amazonas, avistamiento de delfines rosados, caminatas nocturnas y convivencia con comunidades nativas.',
                'itinerary' => "Día 1: Iquitos - Río Amazonas - Lodge\n09:00 - Traslado al puerto\n10:00 - Navegación por el río Amazonas (2h)\n12:00 - Llegada al lodge y almuerzo\n15:00 - Caminata de reconocimiento\n17:00 - Avistamiento de delfines rosados\n19:00 - Cena\n20:30 - Caminata nocturna\n\nDía 2: Selva Profunda\n06:00 - Observación de aves al amanecer\n08:00 - Desayuno\n09:00 - Visita a comunidad nativa\n12:00 - Almuerzo\n15:00 - Pesca de pirañas\n17:00 - Paseo en kayak\n19:00 - Cena\n20:00 - Búsqueda de caimanes\n\nDía 3: Retorno\n06:00 - Último amanecer en la selva\n08:00 - Desayuno y check-out\n09:00 - Navegación de regreso\n11:00 - Llegada a Iquitos",
                'includes' => "• Transporte fluvial ida y vuelta\n• 2 noches en lodge (habitación compartida)\n• Todas las comidas (2 desayunos, 3 almuerzos, 2 cenas)\n• Guía naturalista bilingüe\n• Todas las excursiones mencionadas\n• Botas de jungla\n• Repelente de insectos\n• Agua purificada\n• Botiquín de primeros auxilios",
                'excludes' => "• Vuelos a Iquitos\n• Bebidas alcohólicas\n• Propinas\n• Seguro de viaje\n• Upgrade a habitación privada (+$80)\n• Souvenirs",
                'requirements' => "• Vacuna fiebre amarilla (obligatoria)\n• Repelente de insectos personal\n• Ropa ligera de manga larga\n• Linterna frontal\n• Binoculares (opcional)\n• Cámara resistente al agua\n• Medicamentos personales",
                'cancellation_policy' => "Cancelación gratuita hasta 7 días antes. Entre 7-3 días: 50% reembolso.",
                'refund_policy' => 'partial',
                'cancellation_hours' => 168,
                'price' => 385.00,
                'discount_price' => 320.00,
                'duration_days' => 3,
                'duration_hours' => 0,
                'max_people' => 12,
                'min_people' => 2,
                'difficulty_level' => 'medium',
                'location_city' => 'Iquitos',
                'location_region' => 'Loreto',
                'location_country' => 'Peru',
                'latitude' => -3.749912,
                'longitude' => -73.253479,
                'featured_image' => 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5',
                'rating' => 4.9,
                'total_reviews' => 11,
                'total_bookings' => 14,
                'is_featured' => true,
                'is_active' => true,
                'is_published' => true,
                'published_at' => now(),
                'creation_step' => 5,
                'admin_verified' => true,
                'admin_verified_at' => now(),
                'available_days' => json_encode([1, 3, 5]),
                'quality_checklist' => json_encode([
                    'has_title' => true,
                    'has_description' => true,
                    'has_itinerary' => true,
                    'has_price' => true,
                    'has_images' => true,
                    'min_images_met' => true,
                ]),
                'images' => [
                    'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5',
                    'https://images.unsplash.com/photo-1441974231531-c6227db76b6e',
                    'https://images.unsplash.com/photo-1559827260-dc66d52bef19',
                    'https://images.unsplash.com/photo-1518709268805-4e9042af9f23',
                ],
            ],
            [
                'agency_id' => $agencies[2]->id,
                'category_id' => $categories->where('name', 'Aventura')->first()->id,
                'title' => 'Canopy y Zipline en la Selva Amazónica',
                'description' => 'Vuela sobre la selva amazónica en el circuito de canopy más largo del Perú. 10 plataformas, 2.5km de recorrido y vistas espectaculares del dosel amazónico. Adrenalina pura en medio de la naturaleza.',
                'itinerary' => "08:00 - Recojo del hotel en Iquitos\n08:30 - Traslado al centro de canopy (45 min)\n09:30 - Charla de seguridad y equipamiento\n10:00 - Inicio del circuito de canopy\n12:00 - Almuerzo en la selva\n13:00 - Caminata de aventura\n14:30 - Regreso a Iquitos\n15:30 - Llegada al hotel",
                'includes' => "• Transporte ida y vuelta\n• Equipo de seguridad completo\n• Guía certificado\n• Almuerzo típico\n• Agua y snacks\n• Seguro de accidentes\n• Fotos y videos del recorrido",
                'excludes' => "• Propinas\n• Bebidas alcohólicas\n• Gastos personales",
                'requirements' => "• Edad: 10-65 años\n• Peso máximo: 120kg\n• Buena salud general\n• No apto para embarazadas\n• No apto para problemas cardíacos\n• Ropa deportiva\n• Calzado cerrado obligatorio",
                'cancellation_policy' => "Cancelación gratuita hasta 48 horas antes.",
                'refund_policy' => 'full',
                'cancellation_hours' => 48,
                'price' => 120.00,
                'discount_price' => 95.00,
                'duration_days' => 0,
                'duration_hours' => 7,
                'max_people' => 10,
                'min_people' => 2,
                'difficulty_level' => 'medium',
                'location_city' => 'Iquitos',
                'location_region' => 'Loreto',
                'location_country' => 'Peru',
                'latitude' => -3.749912,
                'longitude' => -73.253479,
                'featured_image' => 'https://images.unsplash.com/photo-1551632811-561732d1e306',
                'rating' => 4.8,
                'total_reviews' => 7,
                'total_bookings' => 9,
                'is_featured' => false,
                'is_active' => true,
                'is_published' => true,
                'published_at' => now(),
                'creation_step' => 5,
                'admin_verified' => true,
                'admin_verified_at' => now(),
                'available_days' => json_encode([1, 2, 3, 4, 5, 6, 0]),
                'quality_checklist' => json_encode([
                    'has_title' => true,
                    'has_description' => true,
                    'has_itinerary' => true,
                    'has_price' => true,
                    'has_images' => true,
                    'min_images_met' => true,
                ]),
                'images' => [
                    'https://images.unsplash.com/photo-1551632811-561732d1e306',
                    'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b',
                    'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5',
                ],
            ],

            // ========== MÁS TOURS DE DIFERENTES DESTINOS ==========
            [
                'agency_id' => $agencies[0]->id,
                'category_id' => $categories->where('name', 'Aventura')->first()->id,
                'title' => 'Rafting en el Río Urubamba - Nivel II-III',
                'description' => 'Adrenalina en los rápidos del Valle Sagrado. Rafting clase II-III apto para principiantes y familias. Incluye entrenamiento, equipo completo y almuerzo. Paisajes espectaculares del Valle Sagrado.',
                'itinerary' => "08:00 - Recojo del hotel en Cusco\n09:30 - Llegada al río Urubamba\n10:00 - Charla de seguridad y práctica\n10:30 - Inicio de rafting (2 horas)\n12:30 - Almuerzo tipo box lunch\n13:30 - Retorno a Cusco\n15:00 - Llegada a hotel",
                'includes' => "• Transporte ida y vuelta\n• Equipo completo (traje, casco, chaleco, remos)\n• Guía certificado\n• Almuerzo\n• Fotos y videos\n• Seguro de accidentes",
                'excludes' => "• Ropa de cambio\n• Toalla\n• Propinas",
                'requirements' => "• Edad mínima: 12 años\n• Saber nadar\n• Buena salud física\n• No apto para embarazadas\n• Ropa que pueda mojarse",
                'cancellation_policy' => "Cancelación gratuita hasta 24 horas antes.",
                'refund_policy' => 'full',
                'cancellation_hours' => 24,
                'price' => 85.00,
                'discount_price' => 70.00,
                'duration_days' => 0,
                'duration_hours' => 7,
                'max_people' => 24,
                'min_people' => 4,
                'difficulty_level' => 'medium',
                'location_city' => 'Cusco',
                'location_region' => 'Cusco',
                'location_country' => 'Peru',
                'latitude' => -13.311093,
                'longitude' => -72.023964,
                'featured_image' => 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29',
                'rating' => 4.7,
                'total_reviews' => 5,
                'total_bookings' => 7,
                'is_featured' => false,
                'is_active' => true,
                'is_published' => true,
                'published_at' => now(),
                'creation_step' => 5,
                'admin_verified' => true,
                'admin_verified_at' => now(),
                'available_days' => json_encode([1, 2, 3, 4, 5, 6]),
                'quality_checklist' => json_encode([
                    'has_title' => true,
                    'has_description' => true,
                    'has_itinerary' => true,
                    'has_price' => true,
                    'has_images' => true,
                    'min_images_met' => true,
                ]),
                'images' => [
                    'https://images.unsplash.com/photo-1501594907352-04cda38ebc29',
                    'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b',
                    'https://images.unsplash.com/photo-1506905925346-21bda4d32df4',
                ],
            ],
            [
                'agency_id' => $agencies[1]->id,
                'category_id' => $categories->where('name', 'Playas')->first()->id,
                'title' => 'Paracas + Islas Ballestas - Full Day desde Lima',
                'description' => 'Conoce las "Galápagos peruanas". Navegación a las Islas Ballestas, observación de lobos marinos, pingüinos de Humboldt y aves guaneras. Visita a la Reserva Nacional de Paracas y playas.',
                'itinerary' => "04:00 - Salida de Lima\n08:00 - Llegada a Paracas\n08:30 - Embarque a Islas Ballestas (2h)\n11:00 - Visita a la Reserva Nacional\n13:00 - Almuerzo frente al mar\n14:30 - Tiempo libre en playa\n16:00 - Retorno a Lima\n20:00 - Llegada a Lima",
                'includes' => "• Transporte turístico desde Lima\n• Guía profesional\n• Entrada a la Reserva\n• Bote a Islas Ballestas\n• Almuerzo\n• Agua embotellada",
                'excludes' => "• Desayuno\n• Propinas\n• Gastos personales",
                'requirements' => "• Bloqueador solar\n• Gorra y lentes de sol\n• Ropa ligera\n• Cámara fotográfica\n• Efectivo para compras",
                'cancellation_policy' => "Cancelación gratuita hasta 48 horas antes.",
                'refund_policy' => 'full',
                'cancellation_hours' => 48,
                'price' => 110.00,
                'discount_price' => 95.00,
                'duration_days' => 1,
                'duration_hours' => 0,
                'max_people' => 30,
                'min_people' => 4,
                'difficulty_level' => 'easy',
                'location_city' => 'Paracas',
                'location_region' => 'Ica',
                'location_country' => 'Peru',
                'latitude' => -13.843917,
                'longitude' => -76.250778,
                'featured_image' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19',
                'rating' => 4.6,
                'total_reviews' => 8,
                'total_bookings' => 11,
                'is_featured' => true,
                'is_active' => true,
                'is_published' => true,
                'published_at' => now(),
                'creation_step' => 5,
                'admin_verified' => true,
                'admin_verified_at' => now(),
                'available_days' => json_encode([1, 2, 3, 4, 5, 6, 0]),
                'quality_checklist' => json_encode([
                    'has_title' => true,
                    'has_description' => true,
                    'has_itinerary' => true,
                    'has_price' => true,
                    'has_images' => true,
                    'min_images_met' => true,
                ]),
                'images' => [
                    'https://images.unsplash.com/photo-1559827260-dc66d52bef19',
                    'https://images.unsplash.com/photo-1583417319070-4a69db38a482',
                    'https://images.unsplash.com/photo-1505142468610-359e7d316be0',
                ],
            ],
            [
                'agency_id' => $agencies[0]->id,
                'category_id' => $categories->where('name', 'Familia')->first()->id,
                'title' => 'Valle Sagrado Completo con Niños - Tour Familiar',
                'description' => 'Tour familiar por el Valle Sagrado adaptado para niños. Visita Pisac, Ollantaytambo y Chinchero con actividades interactivas. Incluye almuerzo buffet y tiempo en mercados artesanales.',
                'itinerary' => "08:00 - Recojo del hotel\n09:30 - Mirador de Taray\n10:00 - Pisac: ruinas y mercado artesanal\n12:00 - Almuerzo buffet en Urubamba\n14:00 - Ollantaytambo: fortaleza inca\n16:00 - Chinchero: telares y alpacas\n18:00 - Retorno a Cusco",
                'includes' => "• Transporte privado familiar\n• Guía especializado en familias\n• Entradas a todos los sitios\n• Almuerzo buffet con opciones para niños\n• Snacks y agua\n• Actividades interactivas\n• Kit de actividades para niños",
                'excludes' => "• Souvenirs\n• Propinas\n• Bebidas extras",
                'requirements' => "• Apto para todas las edades\n• Ritmo pausado y flexible\n• Protector solar\n• Ropa cómoda\n• Carriolas permitidas",
                'cancellation_policy' => "Cancelación gratuita hasta 24 horas antes.",
                'refund_policy' => 'full',
                'cancellation_hours' => 24,
                'price' => 75.00,
                'discount_price' => 60.00,
                'duration_days' => 1,
                'duration_hours' => 0,
                'max_people' => 8,
                'min_people' => 2,
                'difficulty_level' => 'easy',
                'location_city' => 'Cusco',
                'location_region' => 'Cusco',
                'location_country' => 'Peru',
                'latitude' => -13.311093,
                'longitude' => -72.023964,
                'featured_image' => 'https://images.unsplash.com/photo-1511895426328-dc8714191300',
                'rating' => 4.8,
                'total_reviews' => 4,
                'total_bookings' => 6,
                'is_featured' => false,
                'is_active' => true,
                'is_published' => true,
                'published_at' => now(),
                'creation_step' => 5,
                'admin_verified' => true,
                'admin_verified_at' => now(),
                'available_days' => json_encode([1, 2, 3, 4, 5]),
                'quality_checklist' => json_encode([
                    'has_title' => true,
                    'has_description' => true,
                    'has_itinerary' => true,
                    'has_price' => true,
                    'has_images' => true,
                    'min_images_met' => true,
                ]),
                'images' => [
                    'https://images.unsplash.com/photo-1511895426328-dc8714191300',
                    'https://images.unsplash.com/photo-1526392060635-9d6019884377',
                    'https://images.unsplash.com/photo-1580619305218-8423a7ef79b4',
                ],
            ],
            [
                'agency_id' => $agencies[2]->id,
                'category_id' => $categories->where('name', 'Fotografía')->first()->id,
                'title' => 'Safari Fotográfico en la Amazonía - 2 Días',
                'description' => 'Tour especializado para fotógrafos de naturaleza. Guía fotográfico profesional, mejores horarios de luz, acceso a locaciones exclusivas. Captura la biodiversidad amazónica.',
                'itinerary' => "Día 1:\n05:00 - Salida para luz del amanecer\n06:30 - Sesión fotográfica de aves\n09:00 - Desayuno en lodge\n10:00 - Masterclass de fotografía macro\n14:00 - Golden hour en el río\n19:00 - Fotografía nocturna de fauna\n\nDía 2:\n05:00 - Amanecer en el dosel\n08:00 - Desayuno\n09:00 - Retratos de comunidad nativa\n12:00 - Check-out y retorno",
                'includes' => "• Guía fotográfico profesional\n• 1 noche en lodge\n• Todas las comidas\n• Transporte fluvial\n• Acceso a locaciones exclusivas\n• Masterclass de fotografía\n• Revisión de portafolio",
                'excludes' => "• Equipo fotográfico\n• Seguro de equipo\n• Revelado digital",
                'requirements' => "• Cámara DSLR o mirrorless\n• Lentes variados recomendados\n• Trípode\n• Baterías extra\n• Tarjetas de memoria\n• Bolsas impermeables",
                'cancellation_policy' => "Cancelación hasta 5 días antes: 80% reembolso.",
                'refund_policy' => 'partial',
                'cancellation_hours' => 120,
                'price' => 450.00,
                'discount_price' => 380.00,
                'duration_days' => 2,
                'duration_hours' => 0,
                'max_people' => 6,
                'min_people' => 2,
                'difficulty_level' => 'medium',
                'location_city' => 'Iquitos',
                'location_region' => 'Loreto',
                'location_country' => 'Peru',
                'latitude' => -3.749912,
                'longitude' => -73.253479,
                'featured_image' => 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d',
                'rating' => 4.9,
                'total_reviews' => 3,
                'total_bookings' => 4,
                'is_featured' => false,
                'is_active' => true,
                'is_published' => true,
                'published_at' => now(),
                'creation_step' => 5,
                'admin_verified' => true,
                'admin_verified_at' => now(),
                'available_days' => json_encode([1, 4, 6]),
                'quality_checklist' => json_encode([
                    'has_title' => true,
                    'has_description' => true,
                    'has_itinerary' => true,
                    'has_price' => true,
                    'has_images' => true,
                    'min_images_met' => true,
                ]),
                'images' => [
                    'https://images.unsplash.com/photo-1452587925148-ce544e77e70d',
                    'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5',
                    'https://images.unsplash.com/photo-1441974231531-c6227db76b6e',
                ],
            ],
        ];

        foreach ($tours as $tourData) {
            $images = $tourData['images'];
            unset($tourData['images']);
            
            $tourData['slug'] = Str::slug($tourData['title']);
            $tour = Tour::create($tourData);

            foreach ($images as $index => $imageUrl) {
                TourImage::create([
                    'tour_id' => $tour->id,
                    'image_url' => $imageUrl,
                    'alt_text' => $tour->title,
                    'order' => $index + 1,
                    'is_primary' => $index === 0,
                ]);
            }
        }

        $this->command->info('✅ Tours creados: ' . Tour::count());
        $this->command->info('✅ Imágenes creadas: ' . TourImage::count());
    }
}